server:
  port: 7002
spring:
  application:
    name: service-a
  cloud:
    nacos:
      discovery:
        server-addr: 119.3.123.94:8848
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8847